version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"